# Generated by Django 3.2.7 on 2021-10-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211004_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
