# Generated by Django 3.2.5 on 2021-10-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('name', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(decimal_places=5, max_digits=10)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
