# Generated by Django 3.2 on 2021-10-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_allorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allorders',
            name='product',
        ),
        migrations.AddField(
            model_name='allorders',
            name='product',
            field=models.ManyToManyField(to='webapp.Products'),
        ),
    ]
